name: green_estate
description: A responsive real estate landing page with dark green theme

publish_to: 'none' # Remove this line if you want to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  http: ^0.13.5
  google_fonts: ^4.0.3
  flutter_animate: ^4.5.2
  cached_network_image: ^3.2.3
  scrollable_positioned_list: ^0.3.8
  url_launcher: ^6.3.1
  youtube_player_iframe: ^5.2.1
  flutter_web_plugins:
    sdk: flutter
  js: ^0.6.7

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/f1.jpg
    - assets/images/f2.jpg
    - assets/images/f3.jpg
    - assets/images/f4.jpg
    - assets/images/logo.png
    - assets/images/f6.jpg
    - assets/images/f8.jpg
    - assets/images/f9.jpg
    - assets/images/f11.png
    - assets/images/f12.png
    - assets/images/f13.png
    - assets/images/f14.jpg
    - assets/images/f15.jpg
    - assets/images/f16.jpg
    - assets/images/f17.jpg
    - assets/images/f18.jpg
    - assets/images/f19.jpg
    - assets/images/f20.jpg
    - assets/images/f10.jpg
    - assets/images/f21.jpg
    - assets/images/f22.jpg